const dealsConstants = {
  FETCH_DEALS_LIST_REQUEST: '@deals/FETCH_DEALS_LIST/REQUEST',
  FETCH_DEALS_LIST_SUCCESS: '@deals/FETCH_DEALS_LIST/SUCCESS',
  FETCH_DEALS_LIST_FAILURE: '@deals/FETCH_DEALS_LIST/FAILURE',

  FETCH_DEAL_REQUEST: '@deals/FETCH_DEAL/REQUEST',
  FETCH_DEAL_SUCCESS: '@deals/FETCH_DEAL/SUCCESS',
  FETCH_DEAL_FAILURE: '@deals/FETCH_DEAL/FAILURE'
};
export default dealsConstants;
